# Generated by Django 4.1.2 on 2022-10-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('did', models.IntegerField(blank=True, null=True)),
                ('tot', models.IntegerField(blank=True, null=True)),
                ('flight', models.IntegerField(blank=True, null=True)),
                ('landing', models.IntegerField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=500, null=True)),
                ('pressure', models.CharField(blank=True, max_length=300, null=True)),
                ('altitude', models.CharField(blank=True, max_length=300, null=True)),
                ('rangeheight', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'drone',
                'managed': False,
            },
        ),
    ]
