# Generated by Django 4.1.2 on 2022-10-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
