# Generated by Django 4.1.1 on 2022-10-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(blank=True, max_length=20, null=True)),
                ("key", models.FileField(upload_to="")),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
