# Generated by Django 4.1.1 on 2022-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="keyfield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.FileField(upload_to="post/keys")),
            ],
        ),
    ]
