# Generated by Django 4.1.1 on 2022-10-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_rename_key_keyfield_skey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyfield",
            name="skey",
            field=models.FileField(upload_to="post"),
        ),
    ]
