# Generated by Django 4.1.1 on 2022-10-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_alter_keyfield_skey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyfield",
            name="skey",
            field=models.FileField(upload_to="post/keys"),
        ),
    ]
